Tum: derleme calistirma


derleme:
	g++ -I ./include/ -o ./lib/AVL_Tree_LinkedList.o -c ./src/AVL_Tree_LinkedList.cpp
	g++ -I ./include/ -o ./lib/AVL.o -c ./src/AVL.cpp
	g++ -I ./include/ -o ./lib/AVLTree_Node.o -c ./src/AVLTree_Node.cpp
	g++ -I ./include/ -o ./lib/Node.o -c ./src/Node.cpp
	g++ -I ./include/ -o ./lib/Stack.o -c ./src/Stack.cpp
	g++ -I ./include/ -o ./lib/StackNode.o -c ./src/StackNode.cpp
	g++ -I ./include/ -o ./bin/main ./lib/AVL_Tree_LinkedList.o ./lib/AVL.o ./lib/AVLTree_Node.o ./lib/Node.o ./lib/Stack.o ./lib/StackNode.o ./src/main.cpp
	
calistirma:
	cls
	./bin/main

